DROP TABLE SM_STD_CD;

CREATE TABLE SM_STD_CD(
	GRP_CD			VARCHAR(8) NOT NULL COMMENT '그룹코드',
	GRP_NM			VARCHAR(8) NOT NULL COMMENT '그룹코드이름',
	CD				VARCHAR(10) NOT NULL COMMENT '코드',
	CD_NM			VARCHAR(100) COMMENT '코드명',
	CD_DESC			VARCHAR(300) COMMENT '코드설명',
	SORT			INT COMMENT '정렬',
	DPLY_YN			VARCHAR(1) default 'Y' COMMENT '전시여부',
	USE_YN			VARCHAR(1) COMMENT '사용여부',
	SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
	SYS_REG_DTIME	DATETIMETIME COMMENT '시스템등록일시',
	SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
	SYS_MOD_DTIME	DATETIMETIME COMMENT '시스템수정일시',
	PRIMARY KEY (GRP_CD, CD)
) COMMENT '기준코드';

CREATE TABLE USERS(
	USERS_SEQ			INT auto_increment NOT NULL	COMMENT '시퀀스', 
	USER_ID				VARCHAR(250)	NULL		COMMENT '회원 아이디', 
	USER_NAME			VARCHAR(250)	NULL		COMMENT '회원 이름',
	USER_NIC			VARCHAR(500)	NULL		COMMENT '회원 닉네임',
	USER_NIC_CHG_DTIME	DATE			NULL		COMMENT '닉네임변경일',
	USER_PW				VARCHAR(250)	NULL		COMMENT '회원 비밀번호', 
	USER_GENDER			CHAR			NULL		COMMENT '여자:W, 남자:M', 
	USER_AGE			INT				NULL		COMMENT '회원 나이',
	USER_BIRTH			VARCHAR(250)	NULL		COMMENT '생년월일',
	USER_EMAIL			VARCHAR(250)	NULL		COMMENT '회원 이메일', 
	USER_TELL			VARCHAR(250)	NULL		COMMENT '회원 전화번호',
	USER_LV				INT(10)			NULL		COMMENT '유저 레벨',
	LAND_ADDR_BASE		VARCHAR(1000)	NULL		COMMENT '지번 주소',
	LAND_ADDR_DTL		VARCHAR(1000)	NULL		COMMENT '지번 주소 상세',
	LAND_POST_NO		VARCHAR(10)		NULL		COMMENT '지번 우편번호',
	LOAD_ADDR_BASE		VARCHAR(1000)	NULL		COMMENT '도로명 주소',
	LOAD_ADDR_DTL		VARCHAR(1000)	NULL		COMMENT '도로명 주소 상세',
	LOAD_POST_NO		VARCHAR(100)	NULL		COMMENT '도로명 우편번호',
	PASS_WD_CHG_DTIME	DATE			NULL		COMMENT '비밀번호변경 날짜',
	LOGIN_FAIL_CNT		INT(1)			NULL		COMMENT '로그인 실패 횟수',
	LOCK_YN				VARCHAR(1)		NULL		COMMENT '잠김 여부',
	TEMP_PASS_YN		VARCHAR(1)		NULL		COMMENT '임시 비밀번호 여부',
	SNS_CON_TYPE		VARCHAR(200)	NULL		COMMENT 'SNS연동종류',
	SNS_CON_YN			VARCHAR(1)		NULL		COMMENT 'SNS연동여부',
	SNS_SEQ_ID			VARCHAR(200)	NULL		COMMENT 'SNS식별아이디',
	CERT_KEY_VAL		VARCHAR(400)	NULL		COMMENT '인증키값',
	CERT_KEY_DTIME		DATE			NULL		COMMENT '인증키생성일시',
	RCERT_KEY_VAL		VARCHAR(400)	NULL		COMMENT '리프래쉬인증키값',
	RCERT_KEY_DTIME		DATE			NULL		COMMENT '리프래쉬인증키값생성일',
	CERT_TYPE			VARCHAR(400)	NULL		COMMENT '토큰타입',
	EXPIRES_DTIME		VARCHAR(16)		NULL		COMMENT '토큰만료일',
	PROFILE_IMAGE		VARCHAR(400)	NULL		COMMENT '프로필이미지',
	POINT				BIGINT(20)		NULL		COMMENT '포인트',
	UPD_DATE			DATETIME			NULL		COMMENT '수정 일자', 
	REG_DATE			DATETIME			NULL		COMMENT '등록 일자',
	CONSTRAINT USERS_PK PRIMARY KEY (USERS_SEQ)
) COMMENT = '회원';

CREATE TABLE BLACK_LIST(
	USER_IP		VARCHAR(100)	NOT NULL	COMMENT '회원 아이피', 
	USER_ID		VARCHAR(250)	NULL		COMMENT '회원 아이디', 
	USE_YN		CHAR			NULL		COMMENT '사용 유무', 
	REG_DATE	DATETIME		NULL		COMMENT '등록 일자', 
	REG_USER_ID	VARCHAR(250)	NULL		COMMENT '등록 회원 아이디', 
	UPD_DATE	DATETIME		NULL		COMMENT '수정 일자', 
	UPD_USER_ID	VARCHAR(250)	NULL		COMMENT '수정 회원 아이디', 
	CONSTRAINT BLACK_LIST_PK PRIMARY KEY (USER_IP)
) COMMENT '블랙리스트';

/* 이모지 삽입가능 하도록 케릭터셋 변경 */
ALTER DATABASE yourank CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

/* 이모지 삽입가능 하도록 케릭터셋 변경 */
ALTER TABLE SM_STD_CD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE USERS CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;