DROP TABLE SM_STD_CD;

CREATE TABLE SM_STD_CD(
	GRP_CD			VARCHAR(8) NOT NULL COMMENT '그룹코드',
	GRP_NM			VARCHAR(8) NOT NULL COMMENT '그룹코드이름',
	CD				VARCHAR(10) NOT NULL COMMENT '코드',
	CD_NM			VARCHAR(100) COMMENT '코드명',
	CD_DESC			VARCHAR(300) COMMENT '코드설명',
	SORT			INT COMMENT '정렬',
	DPLY_YN			VARCHAR(1) default 'Y' COMMENT '전시여부',
	USE_YN			VARCHAR(1) COMMENT '사용여부',
	SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
	SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
	SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
	SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시',
	PRIMARY KEY (GRP_CD, CD)
) COMMENT '기준코드';

/* 이모지 삽입가능 하도록 케릭터셋 변경 */
ALTER DATABASE yourank CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

/* 이모지 삽입가능 하도록 케릭터셋 변경 */
ALTER TABLE SM_STD_CD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;