/*************************************** 테이블 드랍 ***********************************************/
DROP TABLE STD_CD;

/*************************************** 테이블 생성 ***********************************************/
CREATE TABLE STD_CD(
   GRP_CD			VARCHAR(8) NOT NULL COMMENT '그룹코드',
   CD				VARCHAR(10) NOT NULL COMMENT '코드',
   CD_NM			VARCHAR(100) COMMENT '코드명',
   CD_DESC			VARCHAR(300) COMMENT '코드설명',
   SORT				INT COMMENT '정렬',
   DPLY_YN			VARCHAR(1) default 'Y' COMMENT '전시여부',
   USE_YN			VARCHAR(1) COMMENT '사용여부',
   SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
   SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
   SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
   SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시',
   PRIMARY KEY (GRP_CD, CD)
) COMMENT '기준코드';

CREATE TABLE STD_MENU_INFO(
	MENU_SN			INT AUTO_INCREMENT NOT NULL KEY COMMENT '메뉴일련번호',
    MENU_CD			VARCHAR(100) NOT NULL COMMENT '메뉴코드',
    MENU_PRNT_CD			VARCHAR(100) NOT NULL COMMENT '메뉴코드',
	MENU_NM			VARCHAR(100) NOT NULL COMMENT '메뉴명',
    MENU_DSPY_NM        VARCHAR(400) COMMENT '전시 화명명',
	MENU_URL		VARCHAR(100) COMMENT 'URL',
	MENU_DPTH		INT COMMENT '메뉴댑스',
    SORT				INT COMMENT '정렬',
    MENU_DPLY_YN         VARCHAR(1) DEFAULT 'Y' COMMENT '전시여부',
    USE_YN			VARCHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    MENU_REQ_LGIN_YN     VARCHAR(1) DEFAULT 'N' COMMENT '로그인 필요 여부',
    MENU_REQ_LV          INT DEFAULT 0 COMMENT '사용 레벨',
	SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
	SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
	SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
	SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '기준 메뉴';

CREATE TABLE API_LINK_LOG(
    LOG_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '로그일련번호',
    API_TP_CD		VARCHAR(2) NOT NULL COMMENT 'API유형코드',
    LINK_URL_ADDR	VARCHAR(100) NOT NULL COMMENT '연동URL주소',
    LINK_PARAM		VARCHAR(500) NOT NULL COMMENT '연동파라미터',
    LINK_MSG_CONT	TEXT COMMENT '연동메세지내용',
    SUCC_YN			VARCHAR(1) COMMENT '성공여부',
    ERR_CONT		TEXT COMMENT '에러내용',
   SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
   SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
   SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
   SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT 'API연동로그';

CREATE TABLE BATCH_LOG(
    LOG_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '로그일련번호',
    BATCH_TP_CD	VARCHAR(2) NOT NULL COMMENT '배치유형코드',
    BATCH_TP_NM	VARCHAR(100) NOT NULL COMMENT '배치유형이름',
    BATCH_PARAM	VARCHAR(500) NULL COMMENT '배치파라미터',
    BATCH_MSG_CONT	TEXT COMMENT '배치메세지내용',
    SUCC_YN		VARCHAR(1) COMMENT '성공여부',
    ERR_CONT		TEXT COMMENT '에러내용',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT 'API연동로그';

CREATE TABLE RANK_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    TYPE			VARCHAR(10) NOT NULL COMMENT '타입', /* channel, playlist, video */
    REGION_CD		VARCHAR(10) COMMENT '지역코드',
    CATE_CD			VARCHAR(10) COMMENT '카테고리코드',
    ORG_CATE_CD		VARCHAR(10) COMMENT '카테고리코드',
    RANK_TP_CD		VARCHAR(10) COMMENT '랭킹유형코드',
    CHANNEL_ID		VARCHAR(100) COMMENT '채널아이디',
    VIDEO_ID		VARCHAR(100) COMMENT '비디오아이디',
    TITLE			VARCHAR(500) COMMENT '제목',
    CHANNEL_TITLE	VARCHAR(500) COMMENT '채널제목',
    DESCRIPTION		VARCHAR(1000) COMMENT '설명',
    LIVE_BROADCAST_CONTENT VARCHAR(100),
    PUBLISHED_AT	VARCHAR(30) COMMENT '공개일',
    PUBLISH_TIME	VARCHAR(30) COMMENT '공개일',
    THUMBNAILS_URL1	VARCHAR(100) COMMENT '썸네일URL1',
    THUMBNAILS_URL2	VARCHAR(100) COMMENT '썸네일URL2',
    THUMBNAILS_URL3	VARCHAR(100) COMMENT '썸네일URL3',
    VIEW_COUNT		INT COMMENT 'viewCount',
    LIKE_COUNT		INT COMMENT 'likeCount',
    FAVORITE_COUNT	INT COMMENT 'favoriteCount',
    COMMENT_COUNT	INT COMMENT 'commentCount',
    VIEW_CNT		INT COMMENT '조회수',
    RANKING			INT COMMENT '순위',
    BEFORE_RANKING	INT COMMENT '전주순위',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    DPLY_YN 		VARCHAR(1) default 'N' COMMENT '전시여부',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '랭킹게시판';

/* 이모지 삽입가능 하도록 케릭터셋 변경 */
ALTER DATABASE stock CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

ALTER TABLE API_LINK_LOG CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;