/*************************************** 계정 생성 ***********************************************/
drop DATABASE yourank;

drop user yourank@localhost;

CREATE DATABASE yourank;

CREATE USER yourank@localhost IDENTIFIED BY 'yourank';

GRANT ALL PRIVILEGES ON yourank.* TO yourank@localhost;

alter user 'yourank'@'localhost' identified with mysql_native_password by 'yourank';

flush privileges;

/*************************************** 테이블 드랍 ***********************************************/
DROP TABLE UR_STD_CD;
DROP TABLE UR_STD_MENU_INFO;
DROP TABLE UR_API_LINK_LOG;
DROP TABLE UR_BATCH_LOG;
DROP TABLE UR_RANK_BOARD;
DROP TABLE UR_NTFX_BOARD;
DROP TABLE UR_INTR_BOARD;
DROP TABLE UR_FORUM_BOARD;
DROP TABLE UR_NOTI_BOARD;
DROP TABLE UR_RANK_COMMENT;
DROP TABLE UR_USR_BASE;
DROP TABLE UR_USR_NOTE;
DROP TABLE UR_USR_BOOKMARK;
DROP TABLE UR_POINT_HIST;
DROP TABLE UR_POINT_STD_INFO;
DROP TABLE UR_SC_KEYWORD;
DROP TABLE UR_CT_KEYWORD;
/*************************************** 테이블 생성 ***********************************************/
CREATE TABLE UR_STD_CD(
   GRP_CD			VARCHAR(8) NOT NULL COMMENT '그룹코드',
   CD				VARCHAR(10) NOT NULL COMMENT '코드',
   CD_NM			VARCHAR(100) COMMENT '코드명',
   CD_DESC			VARCHAR(300) COMMENT '코드설명',
   SORT				INT COMMENT '정렬',
   DPLY_YN			VARCHAR(1) default 'Y' COMMENT '전시여부',
   USE_YN			VARCHAR(1) COMMENT '사용여부',
   SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
   SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
   SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
   SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시',
   PRIMARY KEY (GRP_CD, CD)
) COMMENT '기준코드';

CREATE TABLE UR_STD_MENU_INFO(
	MENU_SN			INT AUTO_INCREMENT NOT NULL KEY COMMENT '메뉴일련번호',
    MENU_CD			VARCHAR(100) NOT NULL COMMENT '메뉴코드',
    MENU_PRNT_CD			VARCHAR(100) NOT NULL COMMENT '메뉴코드',
	MENU_NM			VARCHAR(100) NOT NULL COMMENT '메뉴명',
    MENU_DSPY_NM        VARCHAR(400) COMMENT '전시 화명명',
	MENU_URL		VARCHAR(100) COMMENT 'URL',
	MENU_DPTH		INT COMMENT '메뉴댑스',
    SORT				INT COMMENT '정렬',
    MENU_DPLY_YN         VARCHAR(1) DEFAULT 'Y' COMMENT '전시여부',
    USE_YN			VARCHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    MENU_REQ_LGIN_YN     VARCHAR(1) DEFAULT 'N' COMMENT '로그인 필요 여부',
    MENU_REQ_LV          INT DEFAULT 0 COMMENT '사용 레벨',
	SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
	SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
	SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
	SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '기준 메뉴';

CREATE TABLE UR_API_LINK_LOG(
    LOG_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '로그일련번호',
    API_TP_CD		VARCHAR(2) NOT NULL COMMENT 'API유형코드',
    LINK_URL_ADDR	VARCHAR(100) NOT NULL COMMENT '연동URL주소',
    LINK_PARAM		VARCHAR(500) NOT NULL COMMENT '연동파라미터',
    LINK_MSG_CONT	TEXT COMMENT '연동메세지내용',
    SUCC_YN			VARCHAR(1) COMMENT '성공여부',
    ERR_CONT		TEXT COMMENT '에러내용',
   SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
   SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
   SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
   SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT 'API연동로그';

CREATE TABLE UR_BATCH_LOG(
    LOG_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '로그일련번호',
    BATCH_TP_CD	VARCHAR(2) NOT NULL COMMENT '배치유형코드',
    BATCH_TP_NM	VARCHAR(100) NOT NULL COMMENT '배치유형이름',
    BATCH_PARAM	VARCHAR(500) NULL COMMENT '배치파라미터',
    BATCH_MSG_CONT	TEXT COMMENT '배치메세지내용',
    SUCC_YN		VARCHAR(1) COMMENT '성공여부',
    ERR_CONT		TEXT COMMENT '에러내용',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT 'API연동로그';

CREATE TABLE UR_RANK_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    TYPE			VARCHAR(10) NOT NULL COMMENT '타입', /* channel, playlist, video */
    REGION_CD		VARCHAR(10) COMMENT '지역코드',
    CATE_CD			VARCHAR(10) COMMENT '카테고리코드',
    ORG_CATE_CD		VARCHAR(10) COMMENT '카테고리코드',
    RANK_TP_CD		VARCHAR(10) COMMENT '랭킹유형코드',
    CHANNEL_ID		VARCHAR(100) COMMENT '채널아이디',
    VIDEO_ID		VARCHAR(100) COMMENT '비디오아이디',
    TITLE			VARCHAR(500) COMMENT '제목',
    CHANNEL_TITLE	VARCHAR(500) COMMENT '채널제목',
    DESCRIPTION		VARCHAR(1000) COMMENT '설명',
    LIVE_BROADCAST_CONTENT VARCHAR(100),
    PUBLISHED_AT	VARCHAR(30) COMMENT '공개일',
    PUBLISH_TIME	VARCHAR(30) COMMENT '공개일',
    THUMBNAILS_URL1	VARCHAR(100) COMMENT '썸네일URL1',
    THUMBNAILS_URL2	VARCHAR(100) COMMENT '썸네일URL2',
    THUMBNAILS_URL3	VARCHAR(100) COMMENT '썸네일URL3',
    VIEW_COUNT		INT COMMENT 'viewCount',
    LIKE_COUNT		INT COMMENT 'likeCount',
    FAVORITE_COUNT	INT COMMENT 'favoriteCount',
    COMMENT_COUNT	INT COMMENT 'commentCount',
    VIEW_CNT		INT COMMENT '조회수',
    RANKING			INT COMMENT '순위',
    BEFORE_RANKING	INT COMMENT '전주순위',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    DPLY_YN 		VARCHAR(1) default 'N' COMMENT '전시여부',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '랭킹게시판';

CREATE TABLE UR_RANK_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         TEXT COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '랭킹댓글';

CREATE TABLE UR_NTFX_BOARD(
    BBS_SN				BIGINT NOT NULL COMMENT '넷플릭스ID',
    WEEK				VARCHAR(8) NOT NULL COMMENT '기준일',
    CATEGORY			VARCHAR(10) COMMENT '카테고리',  /* tv, films */
    COUNTRY				VARCHAR(5) COMMENT '국가코드',
    RANK				INT COMMENT '순위',
    WEEKS_IN_TOP_TEN	INT COMMENT '탑텐횟수',
    TITLE				VARCHAR(1000) COMMENT '제목',
    EN_TITLE			VARCHAR(1000) COMMENT 'EN제목',
    IMAGE_URL1			VARCHAR(500) COMMENT '썸네일URL1',
    IMAGE_URL2			VARCHAR(500) COMMENT '썸네일URL2',
    YEAR				VARCHAR(10) COMMENT 'year',
    MATURITY_NUMBER		VARCHAR(50) COMMENT 'maturityNumber',
    DUR_STR				VARCHAR(50) COMMENT '시즌',
    GENRE				VARCHAR(500) COMMENT 'genre',
    SYNOPSIS			VARCHAR(500) COMMENT 'synopsis',
    STARRING			VARCHAR(500) COMMENT 'starring',
    CREATORS			VARCHAR(500) COMMENT 'creators',
    VIEW_CNT			INT COMMENT '조회수',
    REC_CNT				INT COMMENT '추천수',
    DEC_CNT				INT COMMENT '비추천수',
    DEL_YN				VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID			VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME		DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID			VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME		DATETIME COMMENT '시스템수정일시',
	PRIMARY KEY (BBS_SN, WEEK)
) COMMENT '넷플릭스랭킹게시판';

CREATE TABLE UR_NTFX_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         TEXT COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '넷플릭스랭킹댓글';

CREATE TABLE UR_INTR_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    CHANNEL_ID		VARCHAR(100) COMMENT '채널아이디',
    TITLE			VARCHAR(500) COMMENT '제목',
    DESCRIPTION		VARCHAR(4000) COMMENT '설명',
    THUMBNAILS_URL1	VARCHAR(300) COMMENT '썸네일URL1',
    THUMBNAILS_URL2	VARCHAR(300) COMMENT '썸네일URL2',
    THUMBNAILS_URL3	VARCHAR(300) COMMENT '썸네일URL3',
    PUBLISHED_AT	VARCHAR(30) COMMENT '공개일',
    CONTENT			TEXT COMMENT '내용',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    CERT_YN			VARCHAR(1) COMMENT '인증여부',
    CERT_ID			VARCHAR(20) COMMENT '인증아이디',
    CERT_DTIME  	DATE COMMENT '인증일시',
    FILE_PATH    	VARCHAR(500) COMMENT '썸네일이미지경로',
    FILE_NAME      	VARCHAR(500) COMMENT '썸네일이미지이름',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '홍보게시판';

CREATE TABLE UR_INTR_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         TEXT COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '홍보댓글';

CREATE TABLE UR_FORUM_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    CATE_CD			VARCHAR(6) COMMENT '카테고리코드',
    CLS_CD			VARCHAR(6) COMMENT '분류코드_CLS50',
    TITLE			VARCHAR(500) COMMENT '제목',
    CONTENT			TEXT COMMENT '내용',
    URL				VARCHAR(100) COMMENT 'URL',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    HOT_YN			VARCHAR(1) COMMENT '핫게여부',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '포럼게시판';

CREATE TABLE UR_FORUM_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         VARCHAR(4000) COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '포럼댓글';

CREATE TABLE UR_FREE_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    CLS_CD			VARCHAR(6) COMMENT '분류코드_CLS10',
    TITLE			VARCHAR(500) COMMENT '제목',
    CONTENT			TEXT COMMENT '내용',
    URL				VARCHAR(100) COMMENT 'URL',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    HOT_YN			VARCHAR(1) COMMENT '핫게여부',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '자유/유머게시판';

CREATE TABLE UR_FREE_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         VARCHAR(4000) COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '자유/유머댓글';

CREATE TABLE UR_JOKE_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    CLS_CD			VARCHAR(6) COMMENT '분류코드_CLS10',
    TITLE			VARCHAR(500) COMMENT '제목',
    CONTENT			TEXT COMMENT '내용',
    URL				VARCHAR(100) COMMENT 'URL',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    HOT_YN			VARCHAR(1) COMMENT '핫게여부',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '유머게시판';

CREATE TABLE UR_JOKE_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         VARCHAR(4000) COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '유머댓글';

CREATE TABLE UR_NEWS_BOARD(
   BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
   CLS_CD			VARCHAR(6) COMMENT '운영카테고리코드_CLS02(운영)_CLS03(뉴스)',
   TITLE			VARCHAR(500) COMMENT '제목',
   URL				VARCHAR(100) COMMENT 'URL',
   CONTENT			TEXT COMMENT '내용',
   VIEW_CNT		    INT COMMENT '조회수',
   REC_CNT			INT COMMENT '추천수',
   DEC_CNT			INT COMMENT '비추천수',
   NOTI_YN			VARCHAR(1) COMMENT '게시여부',
   IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
   DEL_YN			VARCHAR(1) COMMENT '삭제여부',
   SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
   SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
   SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
   SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '뉴스게시판';

CREATE TABLE UR_NEWS_COMMENT(
     CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
     BBS_SN			BIGINT COMMENT '게시판일련번호',
     COMMENT        VARCHAR(4000) COMMENT '코멘트',
     REC_CNT		INT COMMENT '추천수',
     DEC_CNT		INT COMMENT '비추천수',
     SECRET_YN		VARCHAR(1) COMMENT '익명여부',
     SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
     DEL_YN			VARCHAR(1) COMMENT '삭제여부',
     SYS_REGR_ID	VARCHAR(100) COMMENT '시스템등록자아이디',
     SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
     SYS_MODR_ID	VARCHAR(100) COMMENT '시스템수정자아이디',
     SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '뉴스댓글';

CREATE TABLE UR_OPER_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    CLS_CD			VARCHAR(6) COMMENT '운영카테고리코드_CLS02(운영)_CLS03(뉴스)',
    TITLE			VARCHAR(500) COMMENT '제목',
    URL				VARCHAR(100) COMMENT 'URL',
    CONTENT			TEXT COMMENT '내용',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    NOTI_YN			VARCHAR(1) COMMENT '게시여부',
    IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '운영 게시판';

CREATE TABLE UR_OPER_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         VARCHAR(4000) COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '운영 댓글';

CREATE TABLE UR_NOTI_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BD_TP_CD		VARCHAR(6) COMMENT '게시판타입_bdTpCd',
	CATE_CD			VARCHAR(6) COMMENT '카테고리코드_RANK02',
	TITLE			VARCHAR(500) COMMENT '제목',
    URL				VARCHAR(100) COMMENT 'URL',
    CONTENT			TEXT COMMENT '내용',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    STRT_DT			VARCHAR(8) COMMENT '게시시작일',
	END_DT			VARCHAR(8) COMMENT '게시종료일',
	IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '공지 게시판';

CREATE TABLE UR_NOTI_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         VARCHAR(4000) COMMENT '코멘트',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '공지 댓글';

CREATE TABLE UR_YR_BOARD(
    BBS_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    CATE_CD			VARCHAR(6) COMMENT '카테고리코드_YR01',
    CLS_CD			VARCHAR(6) COMMENT '분류코드_CLS7010',
    TITLE			VARCHAR(500) COMMENT '제목',
    CONTENT			TEXT COMMENT '내용',
    URL				VARCHAR(100) COMMENT 'URL',
    GRADE			FLOAT COMMENT '등급_점수',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    HOT_YN			VARCHAR(1) COMMENT '핫게여부',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    IP_ADDR			VARCHAR(100) COMMENT 'IP주소',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '유랭게시판';

CREATE TABLE UR_YR_COMMENT(
    CMT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BBS_SN			BIGINT COMMENT '게시판일련번호',
    COMMENT         VARCHAR(4000) COMMENT '코멘트',
    GRADE			FLOAT COMMENT '등급_점수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    SECRET_YN		VARCHAR(1) COMMENT '익명여부',
    SECRET_ID		VARCHAR(100) COMMENT '익명아이디',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '유랭댓글';

CREATE TABLE UR_USR_BASE (
    USR_BASE_SEQ	BIGINT AUTO_INCREMENT NOT NULL KEY	COMMENT '시퀀스',
    USR_ID	VARCHAR(200)	NOT NULL UNIQUE	COMMENT '아이디',
    USR_LV  VARCHAR(50)     NOT NULL DEFAULT '10' COMMENT '유저권한 10:lv1, 50:서포트, 99:관리자',
    USR_NM	VARCHAR(200)	NOT NULL COMMENT '이름',
    USR_NIC VARCHAR(400)    NOT NULL COMMENT '별명',
    PASS_WD	VARCHAR(200)		COMMENT '비밀번호',
    USR_BIRTH	VARCHAR(200)		COMMENT '생년월일',
    USR_GENDER	VARCHAR(1)		COMMENT '생년월일',
    EMAIL_ADDR	VARCHAR(200)		COMMENT '이메일',
    CELL_NO	VARCHAR(100)		COMMENT '전화번호',
    LAND_ADDR_BASE	VARCHAR(1000)	NULL	COMMENT '지번기본',
    LAND_ADDR_DTL	VARCHAR(1000)	NULL	COMMENT '지번상세',
    LAND_POST_NO	VARCHAR(10)	NULL	COMMENT '지번우편번호',
    LOAD_ADDR_BASE	VARCHAR(1000)	NULL	COMMENT '도로명기본',
    LOAD_ADDR_DTL	VARCHAR(1000)	NULL	COMMENT '도로명상세',
    LOAD_POST_NO	VARCHAR(100)	NULL	COMMENT '도로명우편번호',
    PASS_WD_CHG_DTIME	DATE	NULL	COMMENT '비밀번호 변경일',
    LOGIN_FAIL_CNT	INT(1)	NULL	COMMENT '비밀번호오류횟수',
    LOCK_YN	VARCHAR(1)	NULL	COMMENT '잠김 여부',
    USE_YN	VARCHAR(1)	NULL	COMMENT '사용여부',
    TEMP_PASS_YN	VARCHAR(1)	NULL	COMMENT '임시비밀번호여부',
    SNS_CON_TYPE	VARCHAR(200)	NULL	COMMENT 'SNS연동종류',
    SNS_CON_YN	VARCHAR(1)	NULL	COMMENT 'SNS연동여부',
    SNS_SEQ_ID	VARCHAR(200)	NULL	COMMENT 'SNS식별아이디',
    CERT_KEY_VAL	VARCHAR(400)	NULL	COMMENT '인증키값',
    CERT_KEY_DTIME	DATE	NULL	COMMENT '인증키생성일시',
    RCERT_KEY_VAL	VARCHAR(400)	NULL	COMMENT '리프래쉬인증키값',
    RCERT_KEY_DTIME	DATE	NULL	COMMENT '리프래쉬인증키값생성일',
    CERT_TYPE	VARCHAR(400)	NULL	COMMENT '토큰타입',
    EXPIRES_DTIME	VARCHAR(16)	NULL	COMMENT '토큰만료일',
    PROFILE_IMAGE   VARCHAR(400) NULL   COMMENT '프로필이미지',
    POINT BIGINT COMMENT '포인트',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME	DATETIME COMMENT '시스템수정일시'
) COMMENT '유저';

-- ALTER TABLE UR_USR_BASE DROP COLUMN USR_LV;
-- ALTER TABLE UR_USR_BASE ADD USR_LV VARCHAR(50) NOT NULL DEFAULT '01' COMMENT '유저권한 10:lv1, 50:서포트, 99:관리자';

CREATE TABLE UR_USR_NOTE(
     USR_NOTE_SEQ       BIGINT AUTO_INCREMENT NOT NULL COMMENT '시퀀스',
     SND_USR_ID		    VARCHAR(100) NOT NULL COMMENT '보낸유저_아이디',
     RCV_USR_ID	        VARCHAR(100) NOT NULL COMMENT '받는유저_아이디',
     SEND_DTIME  		DATETIME COMMENT '보낸시각',
     CONTENT			TEXT COMMENT '내용',
     READ_DTIME  		DATETIME COMMENT '읽은시각',
     DEL_YN				VARCHAR(1) COMMENT '삭제여부',
     KEEP_YN			VARCHAR(1) COMMENT '보관여부',
     PRIMARY KEY (USR_NOTE_SEQ),
     INDEX (USR_NOTE_SEQ, RCV_USR_ID, SEND_DTIME)
) COMMENT '쪽지';

CREATE TABLE UR_USR_BOOKMARK(
    BOOKMARK_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    USR_ID	            VARCHAR(200) NOT NULL COMMENT '아이디',
    URL					VARCHAR(100) COMMENT 'URL',
    TITLE				VARCHAR(500) COMMENT '제목',
    CONTENT				TEXT COMMENT '내용',
    SYS_REGR_ID         VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME  	    DATE COMMENT '시스템등록일시'
) COMMENT '북마크';

CREATE TABLE UR_POINT_HIST(
    POINT_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BD_TP_CD			VARCHAR(10) NOT NULL COMMENT '게시판타입_bdTpCd',
	BD_CLS_CD			VARCHAR(10) NOT NULL COMMENT '게시글분류_BASC02',
	BD_SN				BIGINT COMMENT '게시글일련번호_게시글/댓글',
	POINT				INT COMMENT '포인트',
    SYS_REGR_ID			VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME		DATETIME COMMENT '시스템등록일시'
) COMMENT '포인트이력';

CREATE TABLE UR_POINT_STD_INFO(
	BD_TP_CD		VARCHAR(6) COMMENT '게시판타입_bdTpCd',
	BD_CLS_CD		VARCHAR(10) NOT NULL COMMENT '게시글분류_BASC02',
	POINT			INT COMMENT '포인트',
	SYS_REGR_ID			VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME		DATETIME COMMENT '시스템등록일시',
	PRIMARY KEY (BD_TP_CD, BD_CLS_CD)
) COMMENT '포인트기준정보';

CREATE TABLE UR_REC_HIST(
    REC_SN			BIGINT AUTO_INCREMENT NOT NULL KEY COMMENT '일련번호',
    BD_CLS_CD		VARCHAR(10) NOT NULL COMMENT '게시글분류_BASC02',
	BD_TP_CD		VARCHAR(10) NOT NULL COMMENT '유형코드_bdTpCd',
	REC_SEC_CD		VARCHAR(10) NOT NULL COMMENT '추천구분코드_BASC03',
	BD_SN			BIGINT COMMENT '게시글일련번호_게시글/댓글',
    SYS_REGR_ID			VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME		DATETIME COMMENT '시스템등록일시'
) COMMENT '추천히스토리';

CREATE TABLE UR_HOT_BOARD_STD_INFO(
	BD_TP_CD		VARCHAR(6) COMMENT '게시판타입_bdTpCd',
	CATE_CD			VARCHAR(6) COMMENT '카테고리코드_RANK02_확장성용',
	HB_TP_CD		VARCHAR(6) COMMENT '핫게타입_BASC**_확장성용_디폴트(01)',
	STD_VIEW_CNT	INT COMMENT '기준조회수',
	STD_REC_CNT		INT COMMENT '기준추천수',
	STD_CMT_CNT		INT COMMENT '기준댓글갯수',
	SYS_REGR_ID			VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME		DATETIME COMMENT '시스템등록일시',
	PRIMARY KEY (BD_TP_CD, CATE_CD, HB_TP_CD)
) COMMENT '핫게기준정보';

CREATE TABLE UR_HOT_BOARD(
    BBS_SN			BIGINT COMMENT '일련번호',
    BD_TP_CD		VARCHAR(6) COMMENT '게시판타입_bdTpCd',
	HB_TP_CD		VARCHAR(6) COMMENT '핫게타입_BASC04_확장성용_01디폴트',
	TITLE			VARCHAR(500) COMMENT '제목',
    VIEW_CNT		INT COMMENT '조회수',
    REC_CNT			INT COMMENT '추천수',
    DEC_CNT			INT COMMENT '비추천수',
    LINK_URL		VARCHAR(100) COMMENT '링크URL',
    DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME  DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME  DATETIME COMMENT '시스템수정일시',
	PRIMARY KEY (BBS_SN, BD_TP_CD)
) COMMENT '핫게시판';

CREATE TABLE UR_RANK_CATE_DPLY_INFO(
	CATE_CD			VARCHAR(6) COMMENT '카테고리코드_RANK02_확장성용',
	DPLY_YN			VARCHAR(1) default 'N' COMMENT '전시여부',
	SYS_REGR_ID			VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME		DATETIME COMMENT '시스템등록일시',
	PRIMARY KEY (CATE_CD)
) COMMENT '랭킹전시정보';

CREATE TABLE UR_SC_KEYWORD(
	KEYWORD_SN BIGINT AUTO_INCREMENT COMMENT '일련번호',
	STD_DT			VARCHAR(8) COMMENT '기준일자',
	KEYWORD_CONT 	VARCHAR(1000) COMMENT '키워드 내용',
    CNT			    INT COMMENT '횟수',
	CLAN_YN			VARCHAR(1) DEFAULT 'N' COMMENT '정제여부',
	DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME  	DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME  	DATETIME COMMENT '시스템수정일시',
    PRIMARY KEY (KEYWORD_SN)
) COMMENT '검색 키워드';

CREATE TABLE UR_CT_KEYWORD(
	KEYWORD VARCHAR(100) COMMENT '키워드',
	STD_DT			VARCHAR(8) COMMENT '기준일자_월간이면YYYYMM',
	CATE_CD			VARCHAR(10) COMMENT '카테고리코드',
	RANK_TP_CD		VARCHAR(10) COMMENT '랭킹유형코드',
	CNT			INT COMMENT '횟수',
	DEL_YN			VARCHAR(1) COMMENT '삭제여부',
    SYS_REGR_ID		VARCHAR(100) COMMENT '시스템등록자아이디',
    SYS_REG_DTIME  DATETIME COMMENT '시스템등록일시',
    SYS_MODR_ID		VARCHAR(100) COMMENT '시스템수정자아이디',
    SYS_MOD_DTIME  DATETIME COMMENT '시스템수정일시',
    PRIMARY KEY (STD_DT, CATE_CD, RANK_TP_CD, KEYWORD)
) COMMENT '카테고리 키워드';

/* 이모지 삽입가능 하도록 케릭터셋 변경 */
ALTER DATABASE stock CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

ALTER TABLE UR_API_LINK_LOG CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_BATCH_LOG CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_FORUM_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_FORUM_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_HOT_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_HOT_BOARD_STD_INFO CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_INTR_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_INTR_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_NEWS_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_NEWS_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_OPER_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_OPER_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_NOTI_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_NOTI_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_FREE_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_FREE_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_JOKE_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_JOKE_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_POINT_HIST CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_POINT_STD_INFO  CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_RANK_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_RANK_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_REC_HIST CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_STD_CD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_STD_MENU_INFO CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_MPNG_MENU_SCRN CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_USR_BASE CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_USR_BOOKMARK CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_USR_NOTE CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_YR_BOARD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_YR_COMMENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_SC_KEYWORD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE UR_CT_KEYWORD CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
